server:
  port: 30010

spring:
  application:
    name: producer-sample-service
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

swagger:
  ui:
    enabled: true
    title: 生产数据范例
    version: 1.0.0-SNAPSHOT




